### ISSUE TITLE
Scroll problem 

### ISSUE THREAD

**Issue by Pythondara** [Renset/macai#1] opened 2023-03-24 15:21 UTC
when you try to scroll down or up, the application starts scrolling up or down endlessly, you can use the up and down arrows, but this does not work right away

**Comment by Renset** [comment] 2023-03-25 09:46
Hey, @Pythondara thanks for reporting the first issue! I couldn't reproduce this problem yet but will try to investigate the code for possible root cause

**Comment by Renset** [comment] 2023-03-26 20:34
I got detailed debug info and data from @Pythondara, however, I couldn't reproduce the issue on the following environment:
Macbook Air M1, macOS Monterey
Macbook Pro Intel, macOS Ventura

Probably, the problem has been fixed in the latest build. This is closed, however, can be reopened if additional info will be added.

**Closed by Renset** 2023-03-26 20:34 UTC
Labels: not reproduced
